image: Visual Studio 2019

nuget:
  project_feed: true

install:
   # .NET Core SDK binaries
  - ps: $urlCurrent = "https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/5.0.2xx/dotnet-sdk-latest-win-x64.zip"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: $tempFileCurrent = [System.IO.Path]::GetTempFileName()
  - ps: (New-Object System.Net.WebClient).DownloadFile($urlCurrent, $tempFileCurrent)
  - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFileCurrent, $env:DOTNET_INSTALL_DIR)
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
  - ps: $env:MinorVersion = "0.$($env:appveyor_build_number)"
  - ps: $env:VersionSuffix = "-pre"
  - ps: dotnet pack src/toolkit/Community.VisualStudio.Toolkit.14.0/Community.VisualStudio.Toolkit.14.0.csproj /p:configuration=Release /p:ContinuousIntegrationBuild=true
  - ps: dotnet pack src/toolkit/Community.VisualStudio.Toolkit.15.0/Community.VisualStudio.Toolkit.15.0.csproj /p:configuration=Release /p:ContinuousIntegrationBuild=true
  - ps: dotnet pack src/toolkit/Community.VisualStudio.Toolkit.16.0/Community.VisualStudio.Toolkit.16.0.csproj /p:configuration=Release /p:ContinuousIntegrationBuild=true
  - ps: dotnet pack src/toolkit/Community.VisualStudio.Toolkit.17.0/Community.VisualStudio.Toolkit.17.0.csproj /p:configuration=Release /p:ContinuousIntegrationBuild=true
  - ps: dotnet pack src/analyzers/Community.VisualStudio.Toolkit.Analyzers/Community.VisualStudio.Toolkit.Analyzers.csproj /p:configuration=Release /p:ContinuousIntegrationBuild=true

test_script:
  - dotnet test test/toolkit/Community.VisualStudio.Toolkit.UnitTests/Community.VisualStudio.Toolkit.UnitTests.csproj
  - dotnet test test/analyzers/Community.VisualStudio.Toolkit.Analyzers.UnitTests/Community.VisualStudio.Toolkit.Analyzers.UnitTests.csproj

artifacts:
  - path: src\**\*.nupkg
    name: NuGet package

  - path: src\**\*.snupkg
    name: Symbol package

deploy:
  - provider: NuGet
    artifact: /NuGet/
    api_key:
      secure: ykKSUjAVYCP1SdG2u5b7S7jiRhFrTBbnwdvwLYmY6T6sivZk33zHuPEQGQz6gp7X
    on:
      branch: master
      appveyor_repo_commit_message_extended: /\[release\]/
